config/routes.rb
Rails.application.routes.draw do



  get 'static_pages/index'
  get 'static_pages/secret'
  resources :event
  resources :user , only: [:show]
  root to: 'event#index'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  validates :start_date, presence: true
  validate :start_must_be_future
  validates :duration,
    presence: true,
    numericality: { only_integer: true, greater_than: 0 }
  validate :duration_must_be_multiple_of_5
  validates :title,
    presence: true,
    length: { minimum: 5, maximum: 140 }
  validates :description,
    presence: true,
    length: { minimum: 20, maximum: 1000 }
  validates :price,
    presence: true,
    numericality: { only_integer: true, greater_than: 1, less_than_or_equal_to: 1000 }
  validates :location, presence: true

  belongs_to :admin, class_name: "User"

  has_many :participations, dependent: :destroy
  has_many :participants, through: :participations, class_name: "User"

  private

  #Valider que la date de début est bien dans le futur
  def start_must_be_future #A utilser à l'occasion
    return if start_date.blank? #On sort de la boucle si start_date est vide

    if start_date < Time.now
      errors.add(:start_date, "cannot be past")
    end
  end

  #Duration is multiple of 5
  def duration_must_be_multiple_of_5
    return if duration.blank? #On sort si la fonction est vide

    if duration % 5 != 0
      errors.add(:duration, "Duration has to be multiple of 5")
    end

  end


end

app/models/participation.rb
class Participation < ApplicationRecord
  belongs_to :event
  belongs_to :participant, class_name: "User"

  after_create :new_participant_email

  def new_participant_email
    ParticipationMailer.new_participant_email(self.participant,self.event).deliver_now
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :events, foreign_key: 'admin_id', class_name: "Event", dependent: :destroy
  has_many :participations, foreign_key: 'participant_id', class_name: "Participation", dependent: :destroy
  has_many :events, through: :participations

  after_create :welcome_send

  def welcome_send
    UserMailer.welcome_email(self).deliver_now
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_devise_parameters, if: :devise_controller?

  def configure_devise_parameters
    devise_parameter_sanitizer.permit(:sign_up) {|u| u.permit(:first_name, :last_name, :is_alive, :email, :password, :password_confirmation)}
    devise_parameter_sanitizer.permit(:account_update) {|u| u.permit(:first_name, :last_name, :is_alive, :email, :password, :password_confirmation)}
  end

end

app/controllers/event_controller.rb
class EventController < ApplicationController
  def index
    @events = Event.all
  end

  def new
  end

  def show

  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  before_action :authenticate_user!, only: [:secret]
  
  def index
  end

  def secret
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def show
    @user = current_user
    @events = []

    Event.where(admin_id: current_user.id).find_each do |my_event|
      @events << my_event
    end

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/event_helper.rb
module EventHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/event/create.html.erb
<h1>Event#create</h1>
<p>Find me in app/views/event/create.html.erb</p>

app/views/event/destroy.html.erb
<h1>Event#destroy</h1>
<p>Find me in app/views/event/destroy.html.erb</p>

app/views/event/edit.html.erb
<h1>Event#edit</h1>
<p>Find me in app/views/event/edit.html.erb</p>

app/views/event/index.html.erb
<!-- Affichage principal et des tous les gossips-->

<div class="jumbotron jumbotron-fluid jumbotron-hero" style="height:100vh;">
  <h1 class="display-4">Bienvenue chez EventBrite</h1>
  <p class="lead">La communauté qui vous sort de la routine....</p>
  <hr class="my-4">
  <p>Accèder aux événements les plus selects et de votre région en un clic. </p>
</div>

<div class="container">

  <br>
  <h1>Nos événements</h1>
  <br>

  <!-- Afficher le contenu des events -->
  <div class="card-columns">
    <% @events.each_with_index do |event,index| %>
      <div class="card">
        <div class="card-body">
          <h5 class="card-title"><%= event.title %></h5>
          <p class="card-text text-right">Commence le <%= event.start_date.to_formatted_s(:short) %></p>
          <p class="card-text"> <%= event.description %></p><br>
          <%= link_to "consulter", event_path(event.id), class: "card-link btn btn-primary text-right" %>
          <br><br>
          <p class="card-text"><small class="text-muted"> Créé le <%= event.created_at %></small></p>
        </div>
      </div>
      <br>
    <% end %>
  </div>

</div>

app/views/event/new.html.erb
<h1>Event#new</h1>
<p>Find me in app/views/event/new.html.erb</p>

app/views/event/update.html.erb
<h1>Event#update</h1>
<p>Find me in app/views/event/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EventbriteLikeProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.min.css" rel="stylesheet">

    <!-- Scripts JQuery -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <!-- Ajout d'une navbar -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <%= link_to "EventBrite-Like", root_path, class: "navbar-brand mb-0 h1" %>

      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <%= link_to "Créer un Event", new_event_path, class: "nav-link" %>
          </li>

        </ul>
      </div>

        <% if user_signed_in?  %>
          <div class="collapse navbar-collapse">
            <ul class="navbar-nav ml-auto">
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <img src="https://s3.eu-central-1.amazonaws.com/bootstrapbaymisc/blog/24_days_bootstrap/fox.jpg" width="30" height="30" class="rounded-circle">
                </a>
                <div class="dropdown-menu pr-3" aria-labelledby="navbarDropdownMenuLink">
                  <a class="dropdown-item" href="<%= user_path(current_user.id) %>">Mon compte</a>
                  <a class="dropdown-item" href="<%= destroy_user_session_path %>" data-method="delete" >Déconnexion</a>
                </div>
              </li>
            </ul>
          </div>

        <% else  %>
          <div class="dropdown">
            <button class="btn btn-secondary btn-sm dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Connexion
            </button>
            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
              <a class="dropdown-item" href="<%= new_user_session_path %>">Se connecter</a>
              <a class="dropdown-item" href="<%= new_user_registration_path %>">Créer un compte</a>
            </div>
          </div>

        <% end  %>

    </nav>



    <%= yield %>
  </body>
</html>

app/views/static_pages/index.html.erb
<ul>
  <% if user_signed_in? %>
    <li>
      <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
    </li>

    <li>
      Voici ton email : <%= current_user.email %>
    </li>

    <li>
      <%= link_to "Secret page", static_pages_secret_path %>
    </li>

    <li>
      <%= link_to "Edit email / password", edit_user_registration_path %>
    </li>

  <% else %>
    <li>
      <%= link_to "Sign in", new_user_session_path %>
    </li>

    <li>
      <%= link_to "Sign up", new_user_registration_path %>
    </li>

  <% end %>
</ul>

app/views/static_pages/secret.html.erb
<h1>StaticPages#secret</h1>
<p>Find me in app/views/static_pages/secret.html.erb</p>

app/views/user/show.html.erb
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<!------ Include the above in your HEAD tag ---------->

<body>
    <div class="container main-secction">
        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12 image-section">
                <img src="https://i2.wp.com/siegehublot.com/wp-content/uploads/2019/03/plage-palmiers-bateaux-La-cote-sauvage-de-Tangalle-Les-plages-du-Sri-Lanka-et-plus-encore-Asie-Sri-Lanka.jpg?fit=2500%2C1647">
            </div>
            <div class="row user-left-part">
                <div class="col-md-3 col-sm-3 col-xs-12 user-profil-part pull-left">
                    <div class="row ">
                        <div class="col-md-12 col-md-12-sm-12 col-xs-12 user-image text-center">
                            <img src="https://www.jamf.com/jamf-nation/img/default-avatars/generic-user-purple.png" class="rounded-circle">
                        </div>

                    </div>
                </div>
                <div class="col-md-9 col-sm-9 col-xs-12 pull-right profile-right-section">
                    <div class="row profile-right-section-row">
                        <div class="col-md-12 profile-header">
                            <div class="row">
                                <div class="col-md-8 col-sm-6 col-xs-6 profile-header-section1 pull-left">
                                    <h1><%= @user.first_name %> <%= @user.last_name %></h1>

                                </div>
                                <div class="col-md-4 col-sm-6 col-xs-6 profile-header-section1 text-right pull-rigth">
                                    <a href="<%= edit_user_registration_path%>" class="btn btn-primary btn-block">Modifier mon profil</a>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-12">
                            <div class="row">
                                <div class="col-md-8">
                                        <ul class="nav nav-tabs" role="tablist">
                                                <li class="nav-item">
                                                  <a class="nav-link active" href="#profile" role="tab" data-toggle="tab"><i class="fas fa-user-circle"></i> Profil</a>
                                                </li>
                                                <li class="nav-item">
                                                  <a class="nav-link" href="#buzz" role="tab" data-toggle="tab"><i class="fas fa-info-circle"></i> Events</a>
                                                </li>
                                              </ul>

                                              <!-- Tab panes -->
                                              <div class="tab-content">
                                                <div role="tabpanel" class="tab-pane fade show active" id="profile">
                                                        <div class="row">
                                                                <div class="col-md-2">
                                                                    <label>description</label>
                                                                </div>
                                                                <div class="col-md-6">
                                                                    <p><%= @user.description%></p>
                                                                </div>
                                                            </div>
                                                            <div class="row">
                                                                <div class="col-md-2">
                                                                    <label>Nom</label>
                                                                </div>
                                                                <div class="col-md-6">
                                                                    <p><%= @user.first_name %> <%= @user.last_name %></p>
                                                                </div>
                                                            </div>
                                                            <div class="row">
                                                                <div class="col-md-2">
                                                                    <label>Email</label>
                                                                </div>
                                                                <div class="col-md-6">
                                                                    <p><%= @user.email%></p>
                                                                </div>
                                                            </div>

                                                </div>
                                                <div role="tabpanel" class="tab-pane fade" id="buzz">
                                                  <% @events.each_with_index do |event,index| %>
                                                    <div class="card">
                                                      <div class="card-body">
                                                        <h5 class="card-title"><%= event.title %></h5>
                                                        <p class="card-text text-right">Commence le <%= event.start_date.to_formatted_s(:short) %></p>
                                                        <p class="card-text"> <%= event.description %></p><br>
                                                        <%= link_to "consulter", event_path(event.id), class: "card-link btn btn-primary text-right" %>
                                                        <br><br>
                                                        <p class="card-text"><small class="text-muted"> Créé le <%= event.created_at %></small></p>
                                                      </div>
                                                    </div>
                                                    <br>
                                                  <% end %>
                                                </div>

                                              </div>

                                </div>
                                <div class="col-md-4 img-main-rightPart">
                                    <div class="row">
                                        <div class="col-md-12">
                                            <div class="row image-right-part">
                                                <div class="col-md-6 pull-left image-right-detail">
                                                    <h6>Publicité</h6>
                                                </div>
                                            </div>
                                        </div>
                                        <a href="http://camaradecomerciozn.com/">
                                            <div class="col-md-12 image-right">
                                                <img src="http://pluspng.com/img-png/bootstrap-png-bootstrap-512.png">
                                            </div>
                                        </a>
                                        <div class="col-md-12 image-right-detail-section2">

                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="modal fade" id="contact" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="contact">Contactarme</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="form-group">
                        <p for="msj">Se enviará este mensaje a la persona que desea contactar, indicando que te quieres comunicar con el. Para esto debes de ingresar tu información personal.</p>
                    </div>
                    <div class="form-group">
                        <label for="txtFullname">Nombre completo</label>
                        <input type="text" id="txtFullname" class="form-control">
                    </div>
                    <div class="form-group">
                        <label for="txtEmail">Email</label>
                        <input type="text" id="txtEmail" class="form-control">
                    </div>
                    <div class="form-group">
                        <label for="txtPhone">Teléfono</label>
                        <input type="text" id="txtPhone" class="form-control">
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                    <button type="button" class="btn btn-primary" (click)="openModal()" data-dismiss="modal">Guardar</button>
                </div>
            </div>
        </div>
    </div>
</body>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>